pipeline {
    agent any

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Terraform action')
        booleanParam(name: 'AUTO_APPROVE', defaultValue: false, description: 'Skip approval')
    }

    stages {
        stage('Checkout') {
            steps {
                slackSend(color: '#FFFF00', message: "Simi - STARTING BLOG DEPLOYMENT [${env.BUILD_NUMBER}]")
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('blog') {
                    sh 'terraform init -input=false'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('blog') {
                    script {
                        if (params.ACTION == 'destroy') {
                            sh 'terraform plan -destroy -out=tfplan -input=false'
                            slackSend(color: '#FF0000', message: "Simi - DESTROY PLAN READY - BLOG [${env.BUILD_NUMBER}]")
                        } else {
                            sh 'terraform plan -out=tfplan -input=false'
                            slackSend(color: '#FFFF00', message: "Simi - APPLY PLAN READY - BLOG [${env.BUILD_NUMBER}]")
                        }
                    }
                }
            }
        }

        stage('Approval') {
            when {
                expression { return !params.AUTO_APPROVE }
            }
            steps {
                slackSend(color: '#FFFF00', message: "Simi - WAITING FOR APPROVAL - BLOG [${env.BUILD_NUMBER}]")
                input message: "Proceed with ${params.ACTION}?", ok: "Approve"
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('blog') {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }

    post {
        success {
            slackSend(color: '#00FF00', message: "Simi - BLOG ${params.ACTION.toUpperCase()} SUCCESS [${env.BUILD_NUMBER}]")
        }
        failure {
            slackSend(color: '#FF0000', message: "Simi - BLOG ${params.ACTION.toUpperCase()} FAILED [${env.BUILD_NUMBER}]")
        }
    }
}
